### ISSUE TITLE
Error during DecodingSCFile

### ISSUE THREAD

**Issue by mismismo** [MasterDevX/XCoder#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\XCoder\XCoder-master\SC-Decode.py", line 14, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

How can I download PIL modules please?

**Comment by mismismo** [comment]
> 
> 
> Traceback (most recent call last):
> File "C:\Users\Administrator\Downloads\XCoder\XCoder-master\SC-Decode.py", line 14, in
> from PIL import Image
> ImportError: No module named 'PIL'
> 
> How can I download PIL modules please?

**Comment by slightlyepic** [comment]
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Downloads\XCoder\XCoder-master\SC-Decode.py", line 14, in
> > from PIL import Image
> > ImportError: No module named 'PIL'
> > How can I download PIL modules please?

Search command prompt in the search menu and Right Click -> Run as administrator -> type "python" just to make sure python is installed properly, if it says command not recognised then something went wrong with the insallation (assuming you did install Python 3.x) -> Now at this point i assume you have python set up properly -> now type in the console "pip -m install --upgrade pip" just to make sure that pip is fully up to date -> now after thats done, type in the console "pip install Pillow", it should install Pillow (aka PIL aka Python Imaging Library). Once this is done you should be able to run SC-Decode.py

PS - If you dont run command panel as administrator it wont be able to do stuff.
PS again - I encountered another error where the code couldnt take the DataBase and the Byteswriter module from the system folder, i fixed this by copying all the files in the System folder to the main folder

I guess thats it all those error were caused by the failed import statement that should fix it

**Comment by slightlyepic** [comment]
YEAHH and i use Windows 7 32 Bit and Python 3.7.0

**Comment by MasterDevX** [comment]
> Traceback (most recent call last):
> File "C:\Users\Administrator\Downloads\XCoder\XCoder-master\SC-Decode.py", line 14, in 
> from PIL import Image
> ImportError: No module named 'PIL'

You can easily solve the problem by installing Pillow manually by following SlightlyEpic's instruction above, or you can just run Init.py as administrator, this should fix the problem too.
